### ISSUE TITLE
Add Bob's Mods support

### ISSUE THREAD

**Issue by bigyihsuan** [DRY411S/Add-Assembler-Batteries#3]
I used this mod for assembler batteries in my last Bob's Mods save, only to realize that it was using the vanilla recipe, instead of the Bob's Mods one.

So adding in the Bob's Mods recipe would be really nice for Bob's people.

**Comment by DRY411S** [comment]
Thanks for the feedback. I'll take a look at whether I can add this.

**Comment by DRY411S** [comment]
This is now fixed and up on the factorio mod portal for both factorio v0.13 and v0.14.
